// File: services/AlertManagerService.js

/**
 * Service for managing panel alerts with proper indexing and persistence
 */
export class AlertManagerService {
  constructor() {
    this.alertTypes = {
      DUST_ACCUMULATED: 'dust_accumulated',
      DISCOLORATION: 'discoloration', 
      MICRO_CRACKS: 'micro_cracks',
      SEVERE_DEGRADATION: 'severe_degradation',
      MAINTENANCE_NEEDED: 'maintenance_needed',
      PERFORMANCE_DROP: 'performance_drop',
      HOTSPOT_DETECTED: 'hotspot_detected'
    };

    this.severityLevels = {
      LOW: 'low',
      MEDIUM: 'medium', 
      HIGH: 'high',
      CRITICAL: 'critical'
    };

    this.alertSources = {
      COMPUTER_VISION: 'computer_vision',
      MANUAL_INSPECTION: 'manual_inspection',
      THERMAL_INSPECTION: 'thermal_inspection',
      PERFORMANCE_MONITORING: 'performance_monitoring',
      PREDICTIVE_ANALYSIS: 'predictive_analysis',
      SYSTEM: 'system'
    };
  }

  /**
   * Create a new alert with proper indexing
   * @param {Object} alertData - Alert data
   * @returns {Object} Formatted alert with index
   */
  createAlert(alertData) {
    const timestamp = new Date().toISOString();
    const alertId = this.generateAlertId(alertData.type, timestamp);
    
    const alert = {
      id: alertId,
      type: alertData.type || this.alertTypes.MAINTENANCE_NEEDED,
      severity: alertData.severity || this.severityLevels.MEDIUM,
      message: alertData.message || 'Richiede attenzione',
      description: alertData.description || '',
      date: timestamp,
      source: alertData.source || this.alertSources.SYSTEM,
      panelId: alertData.panelId,
      
      // Additional metadata
      metadata: {
        analysisResults: alertData.analysisResults || null,
        recommendedActions: alertData.recommendedActions || [],
        estimatedImpact: alertData.estimatedImpact || null,
        urgencyScore: this.calculateUrgencyScore(alertData),
        autoGenerated: alertData.source === this.alertSources.COMPUTER_VISION || 
                      alertData.source === this.alertSources.PREDICTIVE_ANALYSIS
      },
      
      // Status tracking
      status: 'active', // active, acknowledged, resolved, ignored
      acknowledgedAt: null,
      resolvedAt: null,
      
      // Index for sorting and categorization
      index: this.generateAlertIndex(alertData)
    };

    return alert;
  }

  /**
   * Generate unique alert ID
   * @private
   */
  generateAlertId(type, timestamp) {
    const typeCode = type ? type.substring(0, 3).toUpperCase() : 'GEN';
    const timeCode = new Date(timestamp).getTime().toString().slice(-6);
    const random = Math.random().toString(36).substring(2, 5).toUpperCase();
    
    return `${typeCode}_${timeCode}_${random}`;
  }

  /**
   * Generate alert index for sorting and categorization
   * @private
   */
  generateAlertIndex(alertData) {
    const severityWeight = {
      [this.severityLevels.CRITICAL]: 1000,
      [this.severityLevels.HIGH]: 800,
      [this.severityLevels.MEDIUM]: 600,
      [this.severityLevels.LOW]: 400
    };

    const typeWeight = {
      [this.alertTypes.SEVERE_DEGRADATION]: 900,
      [this.alertTypes.HOTSPOT_DETECTED]: 850,
      [this.alertTypes.MICRO_CRACKS]: 800,
      [this.alertTypes.PERFORMANCE_DROP]: 700,
      [this.alertTypes.DISCOLORATION]: 600,
      [this.alertTypes.DUST_ACCUMULATED]: 500,
      [this.alertTypes.MAINTENANCE_NEEDED]: 400
    };

    const sourceWeight = {
      [this.alertSources.THERMAL_INSPECTION]: 100,
      [this.alertSources.COMPUTER_VISION]: 90,
      [this.alertSources.PREDICTIVE_ANALYSIS]: 80,
      [this.alertSources.PERFORMANCE_MONITORING]: 70,
      [this.alertSources.MANUAL_INSPECTION]: 60,
      [this.alertSources.SYSTEM]: 50
    };

    const severity = severityWeight[alertData.severity] || 500;
    const type = typeWeight[alertData.type] || 500;
    const source = sourceWeight[alertData.source] || 50;
    const timestamp = Date.now() % 10000; // Recent alerts get higher priority

    return severity + type + source + timestamp;
  }

  /**
   * Calculate urgency score for alert
   * @private
   */
  calculateUrgencyScore(alertData) {
    let score = 0;
    
    // Base score from severity
    const severityScores = {
      [this.severityLevels.CRITICAL]: 100,
      [this.severityLevels.HIGH]: 80,
      [this.severityLevels.MEDIUM]: 60,
      [this.severityLevels.LOW]: 40
    };
    
    score += severityScores[alertData.severity] || 50;
    
    // Add score based on type
    const typeScores = {
      [this.alertTypes.SEVERE_DEGRADATION]: 30,
      [this.alertTypes.HOTSPOT_DETECTED]: 25,
      [this.alertTypes.MICRO_CRACKS]: 20,
      [this.alertTypes.PERFORMANCE_DROP]: 15,
      [this.alertTypes.DISCOLORATION]: 10,
      [this.alertTypes.DUST_ACCUMULATED]: 8,
      [this.alertTypes.MAINTENANCE_NEEDED]: 5
    };
    
    score += typeScores[alertData.type] || 5;
    
    // Add recency bonus (more recent = more urgent)
    const hoursOld = alertData.date ? 
      (Date.now() - new Date(alertData.date).getTime()) / (1000 * 60 * 60) : 0;
    
    if (hoursOld < 1) score += 10;
    else if (hoursOld < 24) score += 5;
    else if (hoursOld < 168) score += 2; // Within a week
    
    return Math.min(score, 150); // Cap at 150
  }

  /**
   * Process alerts for a panel, removing duplicates and organizing
   * @param {Array} existingAlerts - Current panel alerts
   * @param {Object} newAlert - New alert to add
   * @returns {Array} Processed alerts array
   */
  processAlertsForPanel(existingAlerts = [], newAlert) {
    let alerts = [...existingAlerts];
    
    // Remove old alerts of the same type and source to avoid duplicates
    alerts = alerts.filter(alert => 
      !(alert.type === newAlert.type && alert.source === newAlert.source)
    );
    
    // Add new alert
    alerts.unshift(newAlert);
    
    // Sort by index (higher index = higher priority)
    alerts.sort((a, b) => (b.index || 0) - (a.index || 0));
    
    // Limit to maximum number of alerts per panel
    const MAX_ALERTS_PER_PANEL = 10;
    if (alerts.length > MAX_ALERTS_PER_PANEL) {
      alerts = alerts.slice(0, MAX_ALERTS_PER_PANEL);
    }
    
    return alerts;
  }

  /**
   * Create alert from computer vision analysis
   * @param {Object} analysisResults - Results from CV analysis
   * @param {string} panelId - Panel ID
   * @returns {Object} Alert object
   */
  createAlertFromVisionAnalysis(analysisResults, panelId) {
    const conditionToType = {
      'dust_accumulated': this.alertTypes.DUST_ACCUMULATED,
      'discoloration': this.alertTypes.DISCOLORATION,
      'micro_cracks': this.alertTypes.MICRO_CRACKS,
      'severe_degradation': this.alertTypes.SEVERE_DEGRADATION
    };

    const conditionToSeverity = {
      'dust_accumulated': this.severityLevels.MEDIUM,
      'discoloration': this.severityLevels.MEDIUM,
      'micro_cracks': this.severityLevels.HIGH,
      'severe_degradation': this.severityLevels.CRITICAL
    };

    const alertData = {
      type: conditionToType[analysisResults.condition] || this.alertTypes.MAINTENANCE_NEEDED,
      severity: conditionToSeverity[analysisResults.condition] || this.severityLevels.MEDIUM,
      message: `Analisi AI: ${analysisResults.description.substring(0, 80)}...`,
      description: analysisResults.description,
      source: this.alertSources.COMPUTER_VISION,
      panelId: panelId,
      analysisResults: analysisResults,
      recommendedActions: analysisResults.recommendations,
      estimatedImpact: {
        efficiencyReduction: analysisResults.efficiencyImpact?.efficiencyReduction || 0,
        economicImpact: analysisResults.efficiencyImpact?.economicImpact || 0
      }
    };

    return this.createAlert(alertData);
  }

  /**
   * Create alert from predictive analysis
   * @param {Object} predictionResults - Results from predictive analysis
   * @param {string} panelId - Panel ID
   * @returns {Object} Alert object
   */
  createAlertFromPredictiveAnalysis(predictionResults, panelId) {
    const stateToSeverity = {
      'issue': this.severityLevels.HIGH,
      'needs_cleaning': this.severityLevels.MEDIUM,
      'needs_inspection': this.severityLevels.MEDIUM,
      'optimal': this.severityLevels.LOW
    };

    const stateToType = {
      'issue': this.alertTypes.PERFORMANCE_DROP,
      'needs_cleaning': this.alertTypes.DUST_ACCUMULATED,
      'needs_inspection': this.alertTypes.MAINTENANCE_NEEDED
    };

    if (predictionResults.state === 'optimal') {
      return null; // No alert needed for optimal state
    }

    const alertData = {
      type: stateToType[predictionResults.state] || this.alertTypes.MAINTENANCE_NEEDED,
      severity: stateToSeverity[predictionResults.state] || this.severityLevels.MEDIUM,
      message: `Analisi predittiva: ${predictionResults.explanation}`,
      description: predictionResults.explanation,
      source: this.alertSources.PREDICTIVE_ANALYSIS,
      panelId: panelId,
      analysisResults: predictionResults,
      recommendedActions: predictionResults.recommendations,
      estimatedImpact: predictionResults.degradationAnalysis?.economicImpact
    };

    return this.createAlert(alertData);
  }

  /**
   * Get alerts summary for system dashboard
   * @param {Array} allPanelsData - All panels data with alerts
   * @returns {Object} Alerts summary
   */
  getSystemAlertsSummary(allPanelsData) {
    const allAlerts = [];
    
    allPanelsData.forEach(panel => {
      if (panel.alerts && panel.alerts.length > 0) {
        panel.alerts.forEach(alert => {
          allAlerts.push({
            ...alert,
            panelName: panel.name
          });
        });
      }
    });

    // Sort by index (priority)
    allAlerts.sort((a, b) => (b.index || 0) - (a.index || 0));

    const summary = {
      totalAlerts: allAlerts.length,
      criticalAlerts: allAlerts.filter(a => a.severity === this.severityLevels.CRITICAL).length,
      highAlerts: allAlerts.filter(a => a.severity === this.severityLevels.HIGH).length,
      mediumAlerts: allAlerts.filter(a => a.severity === this.severityLevels.MEDIUM).length,
      lowAlerts: allAlerts.filter(a => a.severity === this.severityLevels.LOW).length,
      aiGeneratedAlerts: allAlerts.filter(a => 
        a.source === this.alertSources.COMPUTER_VISION || 
        a.source === this.alertSources.PREDICTIVE_ANALYSIS
      ).length,
      topPriorityAlerts: allAlerts.slice(0, 5), // Top 5 most important
      alertsByType: this.categorizeAlertsByType(allAlerts),
      alertsBySource: this.categorizeAlertsBySource(allAlerts)
    };

    return summary;
  }

  /**
   * Categorize alerts by type
   * @private
   */
  categorizeAlertsByType(alerts) {
    const categories = {};
    
    Object.values(this.alertTypes).forEach(type => {
      categories[type] = alerts.filter(alert => alert.type === type).length;
    });

    return categories;
  }

  /**
   * Categorize alerts by source
   * @private
   */
  categorizeAlertsBySource(alerts) {
    const categories = {};
    
    Object.values(this.alertSources).forEach(source => {
      categories[source] = alerts.filter(alert => alert.source === source).length;
    });

    return categories;
  }

  /**
   * Mark alert as acknowledged
   * @param {Object} alert - Alert to acknowledge
   * @returns {Object} Updated alert
   */
  acknowledgeAlert(alert) {
    return {
      ...alert,
      status: 'acknowledged',
      acknowledgedAt: new Date().toISOString()
    };
  }

  /**
   * Mark alert as resolved
   * @param {Object} alert - Alert to resolve
   * @returns {Object} Updated alert
   */
  resolveAlert(alert) {
    return {
      ...alert,
      status: 'resolved',
      resolvedAt: new Date().toISOString()
    };
  }

  /**
   * Get human-readable alert message
   * @param {Object} alert - Alert object
   * @returns {string} Formatted message
   */
  getFormattedAlertMessage(alert) {
    const sourceLabels = {
      [this.alertSources.COMPUTER_VISION]: 'Computer Vision',
      [this.alertSources.PREDICTIVE_ANALYSIS]: 'Analisi Predittiva',
      [this.alertSources.THERMAL_INSPECTION]: 'Ispezione Termica',
      [this.alertSources.PERFORMANCE_MONITORING]: 'Monitoraggio Performance',
      [this.alertSources.MANUAL_INSPECTION]: 'Ispezione Manuale',
      [this.alertSources.SYSTEM]: 'Sistema'
    };

    const source = sourceLabels[alert.source] || 'Sistema';
    return `${source}: ${alert.message}`;
  }
}

export default AlertManagerService;